package dev.inditex.scsoutbox.it.jdbc;

import static org.awaitility.Awaitility.await;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

import dev.inditex.scsoutbox.MessageCaptureTxService;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.stream.function.StreamBridge;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.annotation.DirtiesContext.ClassMode;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.support.TransactionTemplate;

/**
 * Integration test to verify that ErrorMessages generated by Spring Cloud Stream are NOT captured by the outbox pattern.
 *
 * <p>This test validates the filtering logic in {@link dev.inditex.scsoutbox.interceptor.OutboxChannelInterceptor} that prevents
 * system-level error handling messages from being stored in the transactional outbox.
 */
@SpringBootTest(
    classes = {ErrorMessageFilteringIT.TestConfig.class},
    properties = {
        "spring.docker.compose.enabled=true",
        "spring.docker.compose.skip.in-tests=false",
        "spring.cloud.function.definition=myConsumer",
        "spring.cloud.stream.bindings.myConsumer-in-0.destination=outbox",
        "spring.cloud.stream.bindings.myConsumer-in-0.group=outbox",
        "scs-outbox.bindings.inclusions=",
        "scs-outbox.bindings.exclusions=",
        "scs-outbox.publishing.batch-size=10",
        "scs-outbox.publishing.after-commit=false",
        "scs-outbox.publishing.scheduler.fixed-rate=1000",
    })
@DirtiesContext(classMode = ClassMode.AFTER_CLASS)
class ErrorMessageFilteringIT {

  @Configuration
  @EnableAutoConfiguration
  @EnableScheduling
  @EnableTransactionManagement
  @Slf4j
  static class TestConfig {

    /**
     * Simple consumer that throws an exception when processing a message.
     */
    @Bean
    public Consumer<String> myConsumer() {
      return message -> {
        throw new RuntimeException("throw exception in consumer");
      };
    }
  }

  @Autowired
  private StreamBridge streamBridge;

  @MockitoSpyBean
  private MessageCaptureTxService messageCaptureTxService;

  @Autowired
  private TransactionTemplate transactionTemplate;

  /**
   * Validates that when a consumer fails processing a message, the resulting ErrorMessage is NOT captured by the outbox pattern.
   *
   * <p>Test scenario: <ol> <li>Send a message to an output binding (captured in outbox)</li> <li>The scheduled publisher publishes the
   * message to the broker</li> <li>The consumer receives it and throws an exception</li> <li>Spring Cloud Stream generates an ErrorMessage
   * for error handling</li> <li>Verify that only the original message was captured (capture called exactly once)</li> </ol>
   */
  @Test
  void when_consumer_fails_then_error_message_is_not_captured_in_outbox() {
    // 1. Send a message within a transaction (captured synchronously in outbox via the interceptor)
    this.transactionTemplate.executeWithoutResult(status -> this.streamBridge.send("output", "hello-world"));

    // 2. Verify message was captured once (synchronous call during send)
    verify(this.messageCaptureTxService, times(1)).capture(any(), any());

    // 3. Wait for the scheduled publisher to pick up the message, deliver it to the consumer
    // (which throws), and for any error handling to complete. Verify that capture() is never
    // called again — no ErrorMessage was captured.
    await().during(5, TimeUnit.SECONDS).atMost(6, TimeUnit.SECONDS)
        .untilAsserted(() -> verify(this.messageCaptureTxService, times(1)).capture(any(), any()));
  }
}
