version = 1
SPDX-PackageName = "scs-outbox"
SPDX-PackageSupplier = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-PackageDownloadLocation = "https://github.com/InditexTech/scs-outbox"

[[annotations]]
path = [
    "repolinter.json",
    "NOTICE",
    ".gitignore",
    ".gitattributes",
    ".github/CODEOWNERS",
]
SPDX-FileCopyrightText = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "code/**"
SPDX-FileCopyrightText = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".github/**"
SPDX-FileCopyrightText = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "docs/**",
    "README.md"
]
SPDX-FileCopyrightText = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"

