/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dev.inditex.scsoutbox.publish.archive.json;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

/** Event that represents a book created into the system */
@org.apache.avro.specific.AvroGenerated
public class BookCreatedMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4459803347852198677L;

  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
      "{\"type\":\"record\",\"name\":\"BookCreatedMessage\",\"namespace\":\"dev.inditex.karatelabs.book.events.v1\",\"doc\":\"Event that represents a book created into the system\",\"fields\":[{\"name\":\"book_id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<BookCreatedMessage> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BookCreatedMessage> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BookCreatedMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BookCreatedMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BookCreatedMessage> createDecoder(final SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BookCreatedMessage to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BookCreatedMessage from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BookCreatedMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BookCreatedMessage fromByteBuffer(
      final java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  public java.util.UUID book_id;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the schema. If that is desired then one
   * should use <code>newBuilder()</code>.
   */
  public BookCreatedMessage() {
  }

  /**
   * All-args constructor.
   *
   * @param book_id The new value for book_id
   */
  public BookCreatedMessage(final java.util.UUID book_id) {
    this.book_id = book_id;
  }

  @Override
  public SpecificData getSpecificData() {
    return MODEL$;
  }

  @Override
  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter. Applications should not call.
  @Override
  public Object get(final int field$) {
    switch (field$) {
      case 0:
        return this.book_id;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[]{
          new org.apache.avro.Conversions.UUIDConversion(),
          null
      };

  @Override
  public org.apache.avro.Conversion<?> getConversion(final int field) {
    return conversions[field];
  }

  // Used by DatumReader. Applications should not call.
  @Override
  @SuppressWarnings(value = "unchecked")
  public void put(final int field$, final Object value$) {
    switch (field$) {
      case 0:
        this.book_id = (java.util.UUID) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'book_id' field.
   *
   * @return The value of the 'book_id' field.
   */
  public java.util.UUID getBookId() {
    return this.book_id;
  }

  /**
   * Sets the value of the 'book_id' field.
   *
   * @param value the value to set.
   */
  public void setBookId(final java.util.UUID value) {
    this.book_id = value;
  }

  /**
   * Creates a new BookCreatedMessage RecordBuilder.
   *
   * @return A new BookCreatedMessage RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new BookCreatedMessage RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new BookCreatedMessage RecordBuilder
   */
  public static Builder newBuilder(final Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new BookCreatedMessage RecordBuilder by copying an existing BookCreatedMessage instance.
   *
   * @param other The existing instance to copy.
   * @return A new BookCreatedMessage RecordBuilder
   */
  public static Builder newBuilder(final BookCreatedMessage other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for BookCreatedMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BookCreatedMessage>
      implements org.apache.avro.data.RecordBuilder<BookCreatedMessage> {

    private java.util.UUID book_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(final Builder other) {
      super(other);
      if (isValidValue(this.fields()[0], other.book_id)) {
        this.book_id = this.data().deepCopy(this.fields()[0].schema(), other.book_id);
        this.fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing BookCreatedMessage instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(final BookCreatedMessage other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(this.fields()[0], other.book_id)) {
        this.book_id = this.data().deepCopy(this.fields()[0].schema(), other.book_id);
        this.fieldSetFlags()[0] = true;
      }
    }

    /**
     * Gets the value of the 'book_id' field.
     *
     * @return The value.
     */
    public java.util.UUID getBookId() {
      return this.book_id;
    }

    /**
     * Sets the value of the 'book_id' field.
     *
     * @param value The value of 'book_id'.
     * @return This builder.
     */
    public Builder setBookId(final java.util.UUID value) {
      this.validate(this.fields()[0], value);
      this.book_id = value;
      this.fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'book_id' field has been set.
     *
     * @return True if the 'book_id' field has been set, false otherwise.
     */
    public boolean hasBookId() {
      return this.fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'book_id' field.
     *
     * @return This builder.
     */
    public Builder clearBookId() {
      this.book_id = null;
      this.fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BookCreatedMessage build() {
      try {
        final BookCreatedMessage record = new BookCreatedMessage();
        record.book_id = this.fieldSetFlags()[0] ? this.book_id : (java.util.UUID) this.defaultValue(this.fields()[0]);
        return record;
      } catch (final org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (final Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BookCreatedMessage> WRITER$ =
      (org.apache.avro.io.DatumWriter<BookCreatedMessage>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(final java.io.ObjectOutput out)
      throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BookCreatedMessage> READER$ =
      (org.apache.avro.io.DatumReader<BookCreatedMessage>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(final java.io.ObjectInput in)
      throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
