/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dev.inditex.scsoutbox.publish.archive.json;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class Cycle extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2660713656848663733L;

  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
      "{\"type\":\"record\",\"name\":\"Cycle\",\"namespace\":\"dev.inditex.icbcasmng.pipe.cycleData.v2\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Cycle identifier\"},{\"name\":\"distribution_range_id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Distribution range identifier\"},{\"name\":\"week_cycle\",\"type\":\"long\",\"doc\":\"Cycle identifier within the week\"},{\"name\":\"start_date\",\"type\":\"string\",\"doc\":\"Cycle start date,example: '2023-05-24'\"},{\"name\":\"end_date\",\"type\":\"string\",\"doc\":\"Cycle end date, example: '2023-05-26'\"},{\"name\":\"arrival_store_date\",\"type\":\"string\",\"doc\":\"Cycle arrival store date\"},{\"name\":\"closed\",\"type\":\"boolean\",\"doc\":\"closed\"},{\"name\":\"products\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Product\",\"doc\":\"Distributable product information\",\"fields\":[{\"name\":\"distributable_product_id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Distributable Product identifier\"},{\"name\":\"comment\",\"type\":[\"null\",\"string\"],\"doc\":\"Comment\"},{\"name\":\"assignment_type\",\"type\":\"string\",\"doc\":\"Assignment type\",\"enum\":[\"STANDARD\",\"ADVANCE\"]},{\"name\":\"published\",\"type\":\"boolean\",\"doc\":\"published\"}]}}}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<Cycle> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Cycle> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Cycle> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Cycle> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Cycle> createDecoder(final SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Cycle to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Cycle from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Cycle instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Cycle fromByteBuffer(
      final java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Cycle identifier */
  public java.util.UUID id;

  /** Distribution range identifier */
  public java.util.UUID distribution_range_id;

  /** Cycle identifier within the week */
  public long week_cycle;

  /** Cycle start date,example: '2023-05-24' */
  public CharSequence start_date;

  /** Cycle end date, example: '2023-05-26' */
  public CharSequence end_date;

  /** Cycle arrival store date */
  public CharSequence arrival_store_date;

  /** closed */
  public boolean closed;

  public java.util.List<Product> products;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the schema. If that is desired then one
   * should use <code>newBuilder()</code>.
   */
  public Cycle() {
  }

  /**
   * All-args constructor.
   *
   * @param id Cycle identifier
   * @param distribution_range_id Distribution range identifier
   * @param week_cycle Cycle identifier within the week
   * @param start_date Cycle start date,example: '2023-05-24'
   * @param end_date Cycle end date, example: '2023-05-26'
   * @param arrival_store_date Cycle arrival store date
   * @param closed closed
   * @param products The new value for products
   */
  public Cycle(final java.util.UUID id, final java.util.UUID distribution_range_id, final Long week_cycle, final CharSequence start_date,
      final CharSequence end_date,
      final CharSequence arrival_store_date, final Boolean closed, final java.util.List<Product> products) {
    this.id = id;
    this.distribution_range_id = distribution_range_id;
    this.week_cycle = week_cycle;
    this.start_date = start_date;
    this.end_date = end_date;
    this.arrival_store_date = arrival_store_date;
    this.closed = closed;
    this.products = products;
  }

  @Override
  public SpecificData getSpecificData() {
    return MODEL$;
  }

  @Override
  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter. Applications should not call.
  @Override
  public Object get(final int field$) {
    switch (field$) {
      case 0:
        return this.id;
      case 1:
        return this.distribution_range_id;
      case 2:
        return this.week_cycle;
      case 3:
        return this.start_date;
      case 4:
        return this.end_date;
      case 5:
        return this.arrival_store_date;
      case 6:
        return this.closed;
      case 7:
        return this.products;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[]{
          new org.apache.avro.Conversions.UUIDConversion(),
          new org.apache.avro.Conversions.UUIDConversion(),
          null,
          null,
          null,
          null,
          null,
          null,
          null
      };

  @Override
  public org.apache.avro.Conversion<?> getConversion(final int field) {
    return conversions[field];
  }

  // Used by DatumReader. Applications should not call.
  @Override
  @SuppressWarnings(value = "unchecked")
  public void put(final int field$, final Object value$) {
    switch (field$) {
      case 0:
        this.id = (java.util.UUID) value$;
        break;
      case 1:
        this.distribution_range_id = (java.util.UUID) value$;
        break;
      case 2:
        this.week_cycle = (Long) value$;
        break;
      case 3:
        this.start_date = (CharSequence) value$;
        break;
      case 4:
        this.end_date = (CharSequence) value$;
        break;
      case 5:
        this.arrival_store_date = (CharSequence) value$;
        break;
      case 6:
        this.closed = (Boolean) value$;
        break;
      case 7:
        this.products = (java.util.List<Product>) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   *
   * @return Cycle identifier
   */
  public java.util.UUID getId() {
    return this.id;
  }

  /**
   * Sets the value of the 'id' field. Cycle identifier
   *
   * @param value the value to set.
   */
  public void setId(final java.util.UUID value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'distribution_range_id' field.
   *
   * @return Distribution range identifier
   */
  public java.util.UUID getDistributionRangeId() {
    return this.distribution_range_id;
  }

  /**
   * Sets the value of the 'distribution_range_id' field. Distribution range identifier
   *
   * @param value the value to set.
   */
  public void setDistributionRangeId(final java.util.UUID value) {
    this.distribution_range_id = value;
  }

  /**
   * Gets the value of the 'week_cycle' field.
   *
   * @return Cycle identifier within the week
   */
  public long getWeekCycle() {
    return this.week_cycle;
  }

  /**
   * Sets the value of the 'week_cycle' field. Cycle identifier within the week
   *
   * @param value the value to set.
   */
  public void setWeekCycle(final long value) {
    this.week_cycle = value;
  }

  /**
   * Gets the value of the 'start_date' field.
   *
   * @return Cycle start date,example: '2023-05-24'
   */
  public CharSequence getStartDate() {
    return this.start_date;
  }

  /**
   * Sets the value of the 'start_date' field. Cycle start date,example: '2023-05-24'
   *
   * @param value the value to set.
   */
  public void setStartDate(final CharSequence value) {
    this.start_date = value;
  }

  /**
   * Gets the value of the 'end_date' field.
   *
   * @return Cycle end date, example: '2023-05-26'
   */
  public CharSequence getEndDate() {
    return this.end_date;
  }

  /**
   * Sets the value of the 'end_date' field. Cycle end date, example: '2023-05-26'
   *
   * @param value the value to set.
   */
  public void setEndDate(final CharSequence value) {
    this.end_date = value;
  }

  /**
   * Gets the value of the 'arrival_store_date' field.
   *
   * @return Cycle arrival store date
   */
  public CharSequence getArrivalStoreDate() {
    return this.arrival_store_date;
  }

  /**
   * Sets the value of the 'arrival_store_date' field. Cycle arrival store date
   *
   * @param value the value to set.
   */
  public void setArrivalStoreDate(final CharSequence value) {
    this.arrival_store_date = value;
  }

  /**
   * Gets the value of the 'closed' field.
   *
   * @return closed
   */
  public boolean getClosed() {
    return this.closed;
  }

  /**
   * Sets the value of the 'closed' field. closed
   *
   * @param value the value to set.
   */
  public void setClosed(final boolean value) {
    this.closed = value;
  }

  /**
   * Gets the value of the 'products' field.
   *
   * @return The value of the 'products' field.
   */
  public java.util.List<Product> getProducts() {
    return this.products;
  }

  /**
   * Sets the value of the 'products' field.
   *
   * @param value the value to set.
   */
  public void setProducts(final java.util.List<Product> value) {
    this.products = value;
  }

  /**
   * Creates a new Cycle RecordBuilder.
   *
   * @return A new Cycle RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Cycle RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new Cycle RecordBuilder
   */
  public static Builder newBuilder(final Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new Cycle RecordBuilder by copying an existing Cycle instance.
   *
   * @param other The existing instance to copy.
   * @return A new Cycle RecordBuilder
   */
  public static Builder newBuilder(final Cycle other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for Cycle instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Cycle>
      implements org.apache.avro.data.RecordBuilder<Cycle> {

    /** Cycle identifier */
    private java.util.UUID id;

    /** Distribution range identifier */
    private java.util.UUID distribution_range_id;

    /** Cycle identifier within the week */
    private long week_cycle;

    /** Cycle start date,example: '2023-05-24' */
    private CharSequence start_date;

    /** Cycle end date, example: '2023-05-26' */
    private CharSequence end_date;

    /** Cycle arrival store date */
    private CharSequence arrival_store_date;

    /** closed */
    private boolean closed;

    private java.util.List<Product> products;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(final Builder other) {
      super(other);
      if (isValidValue(this.fields()[0], other.id)) {
        this.id = this.data().deepCopy(this.fields()[0].schema(), other.id);
        this.fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(this.fields()[1], other.distribution_range_id)) {
        this.distribution_range_id = this.data().deepCopy(this.fields()[1].schema(), other.distribution_range_id);
        this.fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(this.fields()[2], other.week_cycle)) {
        this.week_cycle = this.data().deepCopy(this.fields()[2].schema(), other.week_cycle);
        this.fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(this.fields()[3], other.start_date)) {
        this.start_date = this.data().deepCopy(this.fields()[3].schema(), other.start_date);
        this.fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(this.fields()[4], other.end_date)) {
        this.end_date = this.data().deepCopy(this.fields()[4].schema(), other.end_date);
        this.fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(this.fields()[5], other.arrival_store_date)) {
        this.arrival_store_date = this.data().deepCopy(this.fields()[5].schema(), other.arrival_store_date);
        this.fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(this.fields()[6], other.closed)) {
        this.closed = this.data().deepCopy(this.fields()[6].schema(), other.closed);
        this.fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(this.fields()[7], other.products)) {
        this.products = this.data().deepCopy(this.fields()[7].schema(), other.products);
        this.fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing Cycle instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(final Cycle other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(this.fields()[0], other.id)) {
        this.id = this.data().deepCopy(this.fields()[0].schema(), other.id);
        this.fieldSetFlags()[0] = true;
      }
      if (isValidValue(this.fields()[1], other.distribution_range_id)) {
        this.distribution_range_id = this.data().deepCopy(this.fields()[1].schema(), other.distribution_range_id);
        this.fieldSetFlags()[1] = true;
      }
      if (isValidValue(this.fields()[2], other.week_cycle)) {
        this.week_cycle = this.data().deepCopy(this.fields()[2].schema(), other.week_cycle);
        this.fieldSetFlags()[2] = true;
      }
      if (isValidValue(this.fields()[3], other.start_date)) {
        this.start_date = this.data().deepCopy(this.fields()[3].schema(), other.start_date);
        this.fieldSetFlags()[3] = true;
      }
      if (isValidValue(this.fields()[4], other.end_date)) {
        this.end_date = this.data().deepCopy(this.fields()[4].schema(), other.end_date);
        this.fieldSetFlags()[4] = true;
      }
      if (isValidValue(this.fields()[5], other.arrival_store_date)) {
        this.arrival_store_date = this.data().deepCopy(this.fields()[5].schema(), other.arrival_store_date);
        this.fieldSetFlags()[5] = true;
      }
      if (isValidValue(this.fields()[6], other.closed)) {
        this.closed = this.data().deepCopy(this.fields()[6].schema(), other.closed);
        this.fieldSetFlags()[6] = true;
      }
      if (isValidValue(this.fields()[7], other.products)) {
        this.products = this.data().deepCopy(this.fields()[7].schema(), other.products);
        this.fieldSetFlags()[7] = true;
      }
    }

    /**
     * Gets the value of the 'id' field. Cycle identifier
     *
     * @return The value.
     */
    public java.util.UUID getId() {
      return this.id;
    }

    /**
     * Sets the value of the 'id' field. Cycle identifier
     *
     * @param value The value of 'id'.
     * @return This builder.
     */
    public Builder setId(final java.util.UUID value) {
      this.validate(this.fields()[0], value);
      this.id = value;
      this.fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'id' field has been set. Cycle identifier
     *
     * @return True if the 'id' field has been set, false otherwise.
     */
    public boolean hasId() {
      return this.fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'id' field. Cycle identifier
     *
     * @return This builder.
     */
    public Builder clearId() {
      this.id = null;
      this.fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'distribution_range_id' field. Distribution range identifier
     *
     * @return The value.
     */
    public java.util.UUID getDistributionRangeId() {
      return this.distribution_range_id;
    }

    /**
     * Sets the value of the 'distribution_range_id' field. Distribution range identifier
     *
     * @param value The value of 'distribution_range_id'.
     * @return This builder.
     */
    public Builder setDistributionRangeId(final java.util.UUID value) {
      this.validate(this.fields()[1], value);
      this.distribution_range_id = value;
      this.fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'distribution_range_id' field has been set. Distribution range identifier
     *
     * @return True if the 'distribution_range_id' field has been set, false otherwise.
     */
    public boolean hasDistributionRangeId() {
      return this.fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'distribution_range_id' field. Distribution range identifier
     *
     * @return This builder.
     */
    public Builder clearDistributionRangeId() {
      this.distribution_range_id = null;
      this.fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'week_cycle' field. Cycle identifier within the week
     *
     * @return The value.
     */
    public long getWeekCycle() {
      return this.week_cycle;
    }

    /**
     * Sets the value of the 'week_cycle' field. Cycle identifier within the week
     *
     * @param value The value of 'week_cycle'.
     * @return This builder.
     */
    public Builder setWeekCycle(final long value) {
      this.validate(this.fields()[2], value);
      this.week_cycle = value;
      this.fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'week_cycle' field has been set. Cycle identifier within the week
     *
     * @return True if the 'week_cycle' field has been set, false otherwise.
     */
    public boolean hasWeekCycle() {
      return this.fieldSetFlags()[2];
    }

    /**
     * Clears the value of the 'week_cycle' field. Cycle identifier within the week
     *
     * @return This builder.
     */
    public Builder clearWeekCycle() {
      this.fieldSetFlags()[2] = false;
      return this;
    }

    /**
     * Gets the value of the 'start_date' field. Cycle start date,example: '2023-05-24'
     *
     * @return The value.
     */
    public CharSequence getStartDate() {
      return this.start_date;
    }

    /**
     * Sets the value of the 'start_date' field. Cycle start date,example: '2023-05-24'
     *
     * @param value The value of 'start_date'.
     * @return This builder.
     */
    public Builder setStartDate(final CharSequence value) {
      this.validate(this.fields()[3], value);
      this.start_date = value;
      this.fieldSetFlags()[3] = true;
      return this;
    }

    /**
     * Checks whether the 'start_date' field has been set. Cycle start date,example: '2023-05-24'
     *
     * @return True if the 'start_date' field has been set, false otherwise.
     */
    public boolean hasStartDate() {
      return this.fieldSetFlags()[3];
    }

    /**
     * Clears the value of the 'start_date' field. Cycle start date,example: '2023-05-24'
     *
     * @return This builder.
     */
    public Builder clearStartDate() {
      this.start_date = null;
      this.fieldSetFlags()[3] = false;
      return this;
    }

    /**
     * Gets the value of the 'end_date' field. Cycle end date, example: '2023-05-26'
     *
     * @return The value.
     */
    public CharSequence getEndDate() {
      return this.end_date;
    }

    /**
     * Sets the value of the 'end_date' field. Cycle end date, example: '2023-05-26'
     *
     * @param value The value of 'end_date'.
     * @return This builder.
     */
    public Builder setEndDate(final CharSequence value) {
      this.validate(this.fields()[4], value);
      this.end_date = value;
      this.fieldSetFlags()[4] = true;
      return this;
    }

    /**
     * Checks whether the 'end_date' field has been set. Cycle end date, example: '2023-05-26'
     *
     * @return True if the 'end_date' field has been set, false otherwise.
     */
    public boolean hasEndDate() {
      return this.fieldSetFlags()[4];
    }

    /**
     * Clears the value of the 'end_date' field. Cycle end date, example: '2023-05-26'
     *
     * @return This builder.
     */
    public Builder clearEndDate() {
      this.end_date = null;
      this.fieldSetFlags()[4] = false;
      return this;
    }

    /**
     * Gets the value of the 'arrival_store_date' field. Cycle arrival store date
     *
     * @return The value.
     */
    public CharSequence getArrivalStoreDate() {
      return this.arrival_store_date;
    }

    /**
     * Sets the value of the 'arrival_store_date' field. Cycle arrival store date
     *
     * @param value The value of 'arrival_store_date'.
     * @return This builder.
     */
    public Builder setArrivalStoreDate(final CharSequence value) {
      this.validate(this.fields()[5], value);
      this.arrival_store_date = value;
      this.fieldSetFlags()[5] = true;
      return this;
    }

    /**
     * Checks whether the 'arrival_store_date' field has been set. Cycle arrival store date
     *
     * @return True if the 'arrival_store_date' field has been set, false otherwise.
     */
    public boolean hasArrivalStoreDate() {
      return this.fieldSetFlags()[5];
    }

    /**
     * Clears the value of the 'arrival_store_date' field. Cycle arrival store date
     *
     * @return This builder.
     */
    public Builder clearArrivalStoreDate() {
      this.arrival_store_date = null;
      this.fieldSetFlags()[5] = false;
      return this;
    }

    /**
     * Gets the value of the 'closed' field. closed
     *
     * @return The value.
     */
    public boolean getClosed() {
      return this.closed;
    }

    /**
     * Sets the value of the 'closed' field. closed
     *
     * @param value The value of 'closed'.
     * @return This builder.
     */
    public Builder setClosed(final boolean value) {
      this.validate(this.fields()[6], value);
      this.closed = value;
      this.fieldSetFlags()[6] = true;
      return this;
    }

    /**
     * Checks whether the 'closed' field has been set. closed
     *
     * @return True if the 'closed' field has been set, false otherwise.
     */
    public boolean hasClosed() {
      return this.fieldSetFlags()[6];
    }

    /**
     * Clears the value of the 'closed' field. closed
     *
     * @return This builder.
     */
    public Builder clearClosed() {
      this.fieldSetFlags()[6] = false;
      return this;
    }

    /**
     * Gets the value of the 'products' field.
     *
     * @return The value.
     */
    public java.util.List<Product> getProducts() {
      return this.products;
    }

    /**
     * Sets the value of the 'products' field.
     *
     * @param value The value of 'products'.
     * @return This builder.
     */
    public Builder setProducts(final java.util.List<Product> value) {
      this.validate(this.fields()[7], value);
      this.products = value;
      this.fieldSetFlags()[7] = true;
      return this;
    }

    /**
     * Checks whether the 'products' field has been set.
     *
     * @return True if the 'products' field has been set, false otherwise.
     */
    public boolean hasProducts() {
      return this.fieldSetFlags()[7];
    }

    /**
     * Clears the value of the 'products' field.
     *
     * @return This builder.
     */
    public Builder clearProducts() {
      this.products = null;
      this.fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Cycle build() {
      try {
        final Cycle record = new Cycle();
        record.id = this.fieldSetFlags()[0] ? this.id : (java.util.UUID) this.defaultValue(this.fields()[0]);
        record.distribution_range_id =
            this.fieldSetFlags()[1] ? this.distribution_range_id : (java.util.UUID) this.defaultValue(this.fields()[1]);
        record.week_cycle = this.fieldSetFlags()[2] ? this.week_cycle : (Long) this.defaultValue(this.fields()[2]);
        record.start_date = this.fieldSetFlags()[3] ? this.start_date : (CharSequence) this.defaultValue(this.fields()[3]);
        record.end_date = this.fieldSetFlags()[4] ? this.end_date : (CharSequence) this.defaultValue(this.fields()[4]);
        record.arrival_store_date = this.fieldSetFlags()[5] ? this.arrival_store_date : (CharSequence) this.defaultValue(this.fields()[5]);
        record.closed = this.fieldSetFlags()[6] ? this.closed : (Boolean) this.defaultValue(this.fields()[6]);
        record.products = this.fieldSetFlags()[7] ? this.products : (java.util.List<Product>) this.defaultValue(this.fields()[7]);
        return record;
      } catch (final org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (final Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Cycle> WRITER$ =
      (org.apache.avro.io.DatumWriter<Cycle>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(final java.io.ObjectOutput out)
      throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Cycle> READER$ =
      (org.apache.avro.io.DatumReader<Cycle>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(final java.io.ObjectInput in)
      throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
