/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dev.inditex.scsoutbox.publish.archive.json;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

/** Distributable product information */
@org.apache.avro.specific.AvroGenerated
public class Product extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6903173095167710534L;

  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
      "{\"type\":\"record\",\"name\":\"Product\",\"namespace\":\"dev.inditex.icbcasmng.pipe.cycleData.v2\",\"doc\":\"Distributable product information\",\"fields\":[{\"name\":\"distributable_product_id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Distributable Product identifier\"},{\"name\":\"comment\",\"type\":[\"null\",\"string\"],\"doc\":\"Comment\"},{\"name\":\"assignment_type\",\"type\":\"string\",\"doc\":\"Assignment type\",\"enum\":[\"STANDARD\",\"ADVANCE\"]},{\"name\":\"published\",\"type\":\"boolean\",\"doc\":\"published\"}]}");

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.UUIDConversion());
  }

  private static final BinaryMessageEncoder<Product> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Product> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   *
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Product> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   *
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Product> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Product> createDecoder(final SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Product to a ByteBuffer.
   *
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Product from a ByteBuffer.
   *
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Product instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Product fromByteBuffer(
      final java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Distributable Product identifier */
  public java.util.UUID distributable_product_id;

  /** Comment */
  public CharSequence comment;

  /** Assignment type */
  public CharSequence assignment_type;

  /** published */
  public boolean published;

  /**
   * Default constructor. Note that this does not initialize fields to their default values from the schema. If that is desired then one
   * should use <code>newBuilder()</code>.
   */
  public Product() {
  }

  /**
   * All-args constructor.
   *
   * @param distributable_product_id Distributable Product identifier
   * @param comment Comment
   * @param assignment_type Assignment type
   * @param published published
   */
  public Product(final java.util.UUID distributable_product_id, final CharSequence comment, final CharSequence assignment_type,
      final Boolean published) {
    this.distributable_product_id = distributable_product_id;
    this.comment = comment;
    this.assignment_type = assignment_type;
    this.published = published;
  }

  @Override
  public SpecificData getSpecificData() {
    return MODEL$;
  }

  @Override
  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter. Applications should not call.
  @Override
  public Object get(final int field$) {
    switch (field$) {
      case 0:
        return this.distributable_product_id;
      case 1:
        return this.comment;
      case 2:
        return this.assignment_type;
      case 3:
        return this.published;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[]{
          new org.apache.avro.Conversions.UUIDConversion(),
          null,
          null,
          null,
          null
      };

  @Override
  public org.apache.avro.Conversion<?> getConversion(final int field) {
    return conversions[field];
  }

  // Used by DatumReader. Applications should not call.
  @Override
  @SuppressWarnings(value = "unchecked")
  public void put(final int field$, final Object value$) {
    switch (field$) {
      case 0:
        this.distributable_product_id = (java.util.UUID) value$;
        break;
      case 1:
        this.comment = (CharSequence) value$;
        break;
      case 2:
        this.assignment_type = (CharSequence) value$;
        break;
      case 3:
        this.published = (Boolean) value$;
        break;
      default:
        throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'distributable_product_id' field.
   *
   * @return Distributable Product identifier
   */
  public java.util.UUID getDistributableProductId() {
    return this.distributable_product_id;
  }

  /**
   * Sets the value of the 'distributable_product_id' field. Distributable Product identifier
   *
   * @param value the value to set.
   */
  public void setDistributableProductId(final java.util.UUID value) {
    this.distributable_product_id = value;
  }

  /**
   * Gets the value of the 'comment' field.
   *
   * @return Comment
   */
  public CharSequence getComment() {
    return this.comment;
  }

  /**
   * Sets the value of the 'comment' field. Comment
   *
   * @param value the value to set.
   */
  public void setComment(final CharSequence value) {
    this.comment = value;
  }

  /**
   * Gets the value of the 'assignment_type' field.
   *
   * @return Assignment type
   */
  public CharSequence getAssignmentType() {
    return this.assignment_type;
  }

  /**
   * Sets the value of the 'assignment_type' field. Assignment type
   *
   * @param value the value to set.
   */
  public void setAssignmentType(final CharSequence value) {
    this.assignment_type = value;
  }

  /**
   * Gets the value of the 'published' field.
   *
   * @return published
   */
  public boolean getPublished() {
    return this.published;
  }

  /**
   * Sets the value of the 'published' field. published
   *
   * @param value the value to set.
   */
  public void setPublished(final boolean value) {
    this.published = value;
  }

  /**
   * Creates a new Product RecordBuilder.
   *
   * @return A new Product RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new Product RecordBuilder
   */
  public static Builder newBuilder(final Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new Product RecordBuilder by copying an existing Product instance.
   *
   * @param other The existing instance to copy.
   * @return A new Product RecordBuilder
   */
  public static Builder newBuilder(final Product other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for Product instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Product>
      implements org.apache.avro.data.RecordBuilder<Product> {

    /** Distributable Product identifier */
    private java.util.UUID distributable_product_id;

    /** Comment */
    private CharSequence comment;

    /** Assignment type */
    private CharSequence assignment_type;

    /** published */
    private boolean published;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(final Builder other) {
      super(other);
      if (isValidValue(this.fields()[0], other.distributable_product_id)) {
        this.distributable_product_id = this.data().deepCopy(this.fields()[0].schema(), other.distributable_product_id);
        this.fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(this.fields()[1], other.comment)) {
        this.comment = this.data().deepCopy(this.fields()[1].schema(), other.comment);
        this.fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(this.fields()[2], other.assignment_type)) {
        this.assignment_type = this.data().deepCopy(this.fields()[2].schema(), other.assignment_type);
        this.fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(this.fields()[3], other.published)) {
        this.published = this.data().deepCopy(this.fields()[3].schema(), other.published);
        this.fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Product instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(final Product other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(this.fields()[0], other.distributable_product_id)) {
        this.distributable_product_id = this.data().deepCopy(this.fields()[0].schema(), other.distributable_product_id);
        this.fieldSetFlags()[0] = true;
      }
      if (isValidValue(this.fields()[1], other.comment)) {
        this.comment = this.data().deepCopy(this.fields()[1].schema(), other.comment);
        this.fieldSetFlags()[1] = true;
      }
      if (isValidValue(this.fields()[2], other.assignment_type)) {
        this.assignment_type = this.data().deepCopy(this.fields()[2].schema(), other.assignment_type);
        this.fieldSetFlags()[2] = true;
      }
      if (isValidValue(this.fields()[3], other.published)) {
        this.published = this.data().deepCopy(this.fields()[3].schema(), other.published);
        this.fieldSetFlags()[3] = true;
      }
    }

    /**
     * Gets the value of the 'distributable_product_id' field. Distributable Product identifier
     *
     * @return The value.
     */
    public java.util.UUID getDistributableProductId() {
      return this.distributable_product_id;
    }

    /**
     * Sets the value of the 'distributable_product_id' field. Distributable Product identifier
     *
     * @param value The value of 'distributable_product_id'.
     * @return This builder.
     */
    public Builder setDistributableProductId(final java.util.UUID value) {
      this.validate(this.fields()[0], value);
      this.distributable_product_id = value;
      this.fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'distributable_product_id' field has been set. Distributable Product identifier
     *
     * @return True if the 'distributable_product_id' field has been set, false otherwise.
     */
    public boolean hasDistributableProductId() {
      return this.fieldSetFlags()[0];
    }

    /**
     * Clears the value of the 'distributable_product_id' field. Distributable Product identifier
     *
     * @return This builder.
     */
    public Builder clearDistributableProductId() {
      this.distributable_product_id = null;
      this.fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'comment' field. Comment
     *
     * @return The value.
     */
    public CharSequence getComment() {
      return this.comment;
    }

    /**
     * Sets the value of the 'comment' field. Comment
     *
     * @param value The value of 'comment'.
     * @return This builder.
     */
    public Builder setComment(final CharSequence value) {
      this.validate(this.fields()[1], value);
      this.comment = value;
      this.fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'comment' field has been set. Comment
     *
     * @return True if the 'comment' field has been set, false otherwise.
     */
    public boolean hasComment() {
      return this.fieldSetFlags()[1];
    }

    /**
     * Clears the value of the 'comment' field. Comment
     *
     * @return This builder.
     */
    public Builder clearComment() {
      this.comment = null;
      this.fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'assignment_type' field. Assignment type
     *
     * @return The value.
     */
    public CharSequence getAssignmentType() {
      return this.assignment_type;
    }

    /**
     * Sets the value of the 'assignment_type' field. Assignment type
     *
     * @param value The value of 'assignment_type'.
     * @return This builder.
     */
    public Builder setAssignmentType(final CharSequence value) {
      this.validate(this.fields()[2], value);
      this.assignment_type = value;
      this.fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'assignment_type' field has been set. Assignment type
     *
     * @return True if the 'assignment_type' field has been set, false otherwise.
     */
    public boolean hasAssignmentType() {
      return this.fieldSetFlags()[2];
    }

    /**
     * Clears the value of the 'assignment_type' field. Assignment type
     *
     * @return This builder.
     */
    public Builder clearAssignmentType() {
      this.assignment_type = null;
      this.fieldSetFlags()[2] = false;
      return this;
    }

    /**
     * Gets the value of the 'published' field. published
     *
     * @return The value.
     */
    public boolean getPublished() {
      return this.published;
    }

    /**
     * Sets the value of the 'published' field. published
     *
     * @param value The value of 'published'.
     * @return This builder.
     */
    public Builder setPublished(final boolean value) {
      this.validate(this.fields()[3], value);
      this.published = value;
      this.fieldSetFlags()[3] = true;
      return this;
    }

    /**
     * Checks whether the 'published' field has been set. published
     *
     * @return True if the 'published' field has been set, false otherwise.
     */
    public boolean hasPublished() {
      return this.fieldSetFlags()[3];
    }

    /**
     * Clears the value of the 'published' field. published
     *
     * @return This builder.
     */
    public Builder clearPublished() {
      this.fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Product build() {
      try {
        final Product record = new Product();
        record.distributable_product_id =
            this.fieldSetFlags()[0] ? this.distributable_product_id : (java.util.UUID) this.defaultValue(this.fields()[0]);
        record.comment = this.fieldSetFlags()[1] ? this.comment : (CharSequence) this.defaultValue(this.fields()[1]);
        record.assignment_type = this.fieldSetFlags()[2] ? this.assignment_type : (CharSequence) this.defaultValue(this.fields()[2]);
        record.published = this.fieldSetFlags()[3] ? this.published : (Boolean) this.defaultValue(this.fields()[3]);
        return record;
      } catch (final org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (final Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Product> WRITER$ =
      (org.apache.avro.io.DatumWriter<Product>) MODEL$.createDatumWriter(SCHEMA$);

  @Override
  public void writeExternal(final java.io.ObjectOutput out)
      throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Product> READER$ =
      (org.apache.avro.io.DatumReader<Product>) MODEL$.createDatumReader(SCHEMA$);

  @Override
  public void readExternal(final java.io.ObjectInput in)
      throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
